kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags:
    - latest
    - main
    # ssh-agent-key:
    #   from_secret: private_key
