kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: josemarbm23/ephemeral-environments 
    auto_tag: true
    tags:
    - latest
    ssh-agent-key:
      from_secret: private_key
