{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: {{ include "Ephemeral-Environments.name" . }}
   labels: 
     {{- include "Ephemeral-Environments.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  - resource:
      name: memory
      target:
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
        type: Utilization
    type: Resource
    {{- end }}    
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        type: Utilization
    type: Resource
    {{- end}}  
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "Ephemeral-Environments.name" . }}
{{- end }}    